name: Docker deploy web app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build docker image
      run: | 
        docker build --platform linux --tag roger1717/mi-webapp:latest -f CI/Dockerfile .
        
    - name: Publish docker image
      run: |
        docker push roger1717/mi-webapp:latest
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tu-webapp-name'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'harry26/mi-webapp:latest'
